bitcoin_analytics:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-thrift
      port: 10000
      schema: iceberg.raw
      threads: 1
      connect_retries: 3
